#!/usr/bin/with-contenv bash

redirect_cmd() {
	if [[ "${DEBUG}" == "true" ]]; then
		"$@"
	else
		"$@" >/dev/null 2>&1
	fi
}

cd / || exit

echo "Starting Bitwarden."
redirect_cmd s6-setuidgid abc \
	bitwarden_rs
